=== MLB-LED-Scoreboard/mlb-led-scoreboard/schemas/coordinates/w128h64.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "128x64 Scoreboard Coordinates",
  "x-indent": "  ",
  "type": "object",
  "required": ["format"],
  "properties": {
    "x-schema": {
      "type": "string",
      "default": "./../schemas/coordinates/w128h64.schema.json",
      "readOnly": true,
      "x-enforceConst": true,
      "x-hidden": true
    },
    "format":       { "$ref": "./_common.schema.json#/$defs/format" },
    "defaults":     { "$ref": "./_common.schema.json#/$defs/defaults" },
    "bases":        { "$ref": "./_common.schema.json#/$defs/bases" },
    "final":        { "$ref": "./_common.schema.json#/$defs/final" },
    "inning":       { "$ref": "./_common.schema.json#/$defs/inning" },
    "outs":         { "$ref": "./_common.schema.json#/$defs/outs" },
    "atbat":        { "$ref": "./_common.schema.json#/$defs/atbat" },
    "batter_count": { "$ref": "./_common.schema.json#/$defs/batter_count" },
    "nohitter":     { "$ref": "./_common.schema.json#/$defs/nohitter" },
    "pregame":      { "$ref": "./_common.schema.json#/$defs/pregame" },
    "standings":    { "$ref": "./_common.schema.json#/$defs/standings" },
    "status":       { "$ref": "./_common.schema.json#/$defs/status" },
    "teams":        { "$ref": "./_common.schema.json#/$defs/teams" },
    "news":         { "$ref": "./_common.schema.json#/$defs/news" },
    "plugins":      { "$ref": "./_common.schema.json#/$defs/plugins" },
    "network":      { "$ref": "./_common.schema.json#/$defs/network" }
  },
  "default": {
    "x-schema": "./../schemas/coordinates/w128h64.schema.json",
    "format": 9.0,
    "defaults": {
      "font_name": "7x13"
    },
    "bases": {
      "1B": { "x": 112, "y": 42, "size": 10 },
      "2B": { "x": 103, "y": 33, "size": 10 },
      "3B": { "x": 94,  "y": 42, "size": 10 }
    },
    "final": {
      "inning":         { "x": 67,  "y": 61 },
      "scrolling_text": { "x": 0,   "y": 44, "width": 128 },
      "nohit_text":     { "x": 1,   "y": 61 },
      "record": {
        "font_name": "4x6",
        "enabled":   false,
        "away": { "x": 30, "y": 13 },
        "home": { "x": 30, "y": 29 }
      }
    },
    "inning": {
      "break": {
        "number":     { "x": 3, "y": 58 },
        "text":       { "x": 3, "y": 44 },
        "show_field": false,
        "due_up": {
          "due":     { "font_name": "5x7", "x": 38, "y": 44 },
          "up":      { "x": 38, "y": 56 },
          "scroll":  { "font_name": "5x7", "x": 0, "y": 52, "width": 128, "enabled": false },
          "divider": { "draw": false, "x": 36, "y_start": 32, "y_end": 64 },
          "loop":    128,
          "leadoff": { "font_name": "7x13", "x": 64, "y": 42, "width": 64 },
          "on_deck": { "x": 64, "y": 52, "width": 64 },
          "in_hole": { "x": 64, "y": 62, "width": 64 }
        }
      },
      "number": {
        "x": 87, "y": 42,
        "nohit":        { "x": 93, "y": 42 },
        "perfect_game": { "x": 93, "y": 42 }
      },
      "arrow": {
        "size": 6,
        "stacked": false,
        "up":   { "x_offset": -11, "y_offset": -8, "x": 78, "y": 36 },
        "down": { "x_offset": -11, "y_offset": -4, "x": 78, "y": 48 }
      }
    },
    "outs": {
      "1": { "x": 95,  "y": 56, "size": 5 },
      "2": { "x": 106, "y": 56, "size": 5 },
      "3": { "x": 118, "y": 56, "size": 5 }
    },
    "atbat": {
      "batter":      { "font_name": "5x7", "x": 1,  "y": 60, "width": 41 },
      "pitcher":     { "font_name": "5x7", "x": 1,  "y": 40, "width": 41 },
      "pitch":       { "font_name": "4x6", "x": 1,  "y": 50, "enabled": true,  "mph": true,  "desc_length": "long" },
      "pitch_count": { "font_name": "4x6", "x": 1,  "y": 50, "enabled": false, "append_pitcher_name": false },
      "batter_order":     { "font_name": "4x6", "x": 1, "y": 60, "enabled": false },
      "batter_stats":     { "font_name": "4x6", "y": 60, "enabled": false, "show_era": false },
      "play_description": { "font_name": "4x6", "x": 44, "y": 50, "width": 49, "enabled": false },
      "loop": 68,
      "strikeout":   { "x": 16, "y": 60, "desc_length": "long", "enabled": true },
      "play_result": { "x": 16, "y": 60, "desc_length": "long", "enabled": true }
    },
    "batter_count": {
      "x": 66, "y": 62,
      "nohit":        { "x": 66, "y": 64 },
      "perfect_game": { "x": 66, "y": 64 }
    },
    "nohitter": { "x": 66, "y": 53, "innings_until_display": 5 },
    "pregame": {
      "scrolling_text": { "x": 0, "y": 46, "width": 128, "warmup": { "x": 0, "y": 46, "width": 128 } },
      "start_time":     { "x": 66, "y": 60 },
      "warmup_text":    { "x": 66, "y": 60 }
    },
    "standings": {
      "start":  1,
      "offset": 12,
      "height": 60,
      "width":  128,
      "divider":    { "x": 32 },
      "stat_title": { "x": 28 },
      "team": {
        "name":       { "x": 1   },
        "record":     { "x": 59  },
        "games_back": { "x": 124 }
      },
      "postseason": {
        "matchup_y_gap": 12,
        "series_x_gap":  32,
        "wc_x_start":    3,
        "wc_y_start":    12,
        "ds_a_y_start":  51,
        "__comment":     "all other coords are based off wild card position"
      }
    },
    "status": {
      "text":           { "x": 64, "y": 46, "short_text": false },
      "scrolling_text": { "x": 0,  "y": 58, "width": 128 }
    },
    "teams": {
      "background": {
        "away": { "width": 128, "height": 16, "x": 0, "y": 0  },
        "home": { "width": 128, "height": 16, "x": 0, "y": 16 }
      },
      "accent": {
        "away": { "width": 2, "height": 16, "x": 0, "y": 0  },
        "home": { "width": 2, "height": 16, "x": 0, "y": 16 }
      },
      "name": {
        "away": { "font_name": "9x18B", "x": 4, "y": 13 },
        "home": { "font_name": "9x18B", "x": 4, "y": 29 },
        "full": true
      },
      "record": {
        "enabled":  false,
        "position": "absolute",
        "away": { "x": 30, "y": 13 },
        "home": { "x": 30, "y": 29 },
        "hide_record_on_high_line_score": false
      },
      "line_score": {
        "away": { "font_name": "9x18B", "x": 124, "y": 13 },
        "home": { "font_name": "9x18B", "x": 124, "y": 29 },
        "show_hits_and_errors":  true,
        "show_abs_challenges":   true,
        "compress_digits":       true,
        "shorten_team_name_on_high_line_score": true,
        "spacing": 5
      },
      "abs_challenges": {
        "away": { "x": 125, "size": 3, "height": 3, "squares": [4, 9]   },
        "home": { "x": 125, "size": 3, "height": 3, "squares": [20, 25] }
      }
    },
    "news": {
      "scrolling_text": { "x": 0,  "y": 60, "width": 128 },
      "time":           { "x": 80, "y": 15 },
      "conditions":     { "x": 80, "y": 30 },
      "temperature":    { "x": 20, "y": 44 },
      "wind_speed":     { "x": 0,  "y": -4 },
      "wind_dir":       { "x": 0,  "y": -4 },
      "wind":           { "x": 80, "y": 44 },
      "weather_icon":   { "x": 6,  "y": 2, "width": 30, "height": 30, "rescale_icon": 2 }
    },
    "plugins": {},
    "network": {
      "font_name":  "4x6",
      "background": { "width": 7, "height": 7, "x": 121, "y": 57 },
      "text":       { "x": 125, "y": 63 }
    }
  }
}

=== MLB-LED-Scoreboard/mlb-led-scoreboard/coordinates/examples/w128h64-verbose.json
{
  "$schema": "./../schemas/coordinates/w128h64.schema.json",
  "format": 9.0,
  "defaults": {
    "font_name": "7x13"
  },
  "bases": {
    "1B": {
      "x": 88,
      "y": 37,
      "size": 12
    },
    "2B": {
      "x": 79,
      "y": 29,
      "size": 12
    },
    "3B": {
      "x": 70,
      "y": 37,
      "size": 12
    }
  },
  "final": {
    "inning": {
      "x": 64,
      "y": 13
    },
    "scrolling_text": {
      "font_name": "5x7",
      "x": 0,
      "y": 25,
      "width": 128
    },
    "nohit_text": {
      "x": 98,
      "y": 12
    },
    "record": {
      "font_name": "4x6",
      "enabled": true,
      "away": {
        "x": 56,
        "y": 39
      },
      "home": {
        "x": 56,
        "y": 57
      }
    }
  },
  "inning": {
    "break": {
      "number": {
        "x": 3,
        "y": 58
      },
      "text": {
        "x": 3,
        "y": 44
      },
      "show_field": true,
      "due_up": {
        "due": {
          "font_name": "5x7",
          "x": 70,
          "y": 12
        },
        "up": {
          "x": 70,
          "y": 24
        },
        "scroll": {
          "font_name": "5x7",
          "x": 0,
          "y": 17,
          "width": 128,
          "enabled": true
        },
        "divider": {
          "draw": false,
          "x": 52,
          "y_start": 28,
          "y_end": 63
        },
        "loop": 128,
        "leadoff": {
          "font_name": "7x13",
          "x": 70,
          "y": 42,
          "width": 58
        },
        "on_deck": {
          "x": 70,
          "y": 52,
          "width": 58
        },
        "in_hole": {
          "x": 70,
          "y": 62,
          "width": 58
        }
      }
    },
    "number": {
      "x": 65,
      "y": 43,
      "nohit": {
        "x": 65,
        "y": 43
      },
      "perfect_game": {
        "x": 65,
        "y": 43
      },
      "font_name": "5x7"
    },
    "arrow": {
      "size": 3,
      "stacked": true,
      "up": {
        "x": 62,
        "y": 29,
        "x_offset": -11,
        "y_offset": -8
      },
      "down": {
        "x": 62,
        "y": 51,
        "x_offset": -11,
        "y_offset": -4
      }
    }
  },
  "outs": {
    "1": {
      "x": 105,
      "y": 46,
      "size": 4
    },
    "2": {
      "x": 114,
      "y": 46,
      "size": 4
    },
    "3": {
      "x": 123,
      "y": 46,
      "size": 4
    }
  },
  "atbat": {
    "batter": {
      "font_name": "5x7",
      "x": 1,
      "y": 10,
      "width": 60
    },
    "pitcher": {
      "font_name": "5x7",
      "x": 1,
      "y": 25,
      "width": 55
    },
    "pitch": {
      "font_name": "4x6",
      "x": 1,
      "y": 50,
      "enabled": false,
      "mph": false,
      "desc_length": "short"
    },
    "pitch_count": {
      "font_name": "4x6",
      "x": 110,
      "y": 25,
      "enabled": true,
      "append_pitcher_name": false
    },
    "batter_order": {
      "font_name": "4x6",
      "x": 1,
      "y": 10,
      "enabled": true
    },
    "batter_stats": {
      "font_name": "4x6",
      "y": 10,
      "enabled": true,
      "show_era": true
    },
    "play_description": {
      "font_name": "4x6",
      "x": 55,
      "y": 61,
      "width": 73,
      "enabled": true
    },
    "loop": 68,
    "strikeout": {
      "x": 16,
      "y": 60,
      "desc_length": "long",
      "enabled": false
    },
    "play_result": {
      "x": 16,
      "y": 60,
      "desc_length": "long",
      "enabled": false
    }
  },
  "batter_count": {
    "x": 105,
    "y": 40,
    "nohit": {
      "x": 105,
      "y": 40
    },
    "perfect_game": {
      "x": 105,
      "y": 40
    },
    "font_name": "5x7"
  },
  "nohitter": {
    "x": 95,
    "y": 25,
    "innings_until_display": 5,
    "font_name": "4x6"
  },
  "pregame": {
    "scrolling_text": {
      "x": 0,
      "y": 20,
      "width": 128,
      "warmup": {
        "x": 0,
        "y": 20,
        "width": 128
      }
    },
    "start_time": {
      "x": 90,
      "y": 60
    },
    "warmup_text": {
      "x": 90,
      "y": 60
    }
  },
  "standings": {
    "start": 1,
    "offset": 12,
    "height": 60,
    "width": 128,
    "divider": {
      "x": 32
    },
    "stat_title": {
      "x": 28
    },
    "team": {
      "name": {
        "x": 1
      },
      "record": {
        "x": 59
      },
      "games_back": {
        "x": 124
      }
    },
    "postseason": {
      "matchup_y_gap": 12,
      "series_x_gap": 32,
      "wc_x_start": 3,
      "wc_y_start": 12,
      "ds_a_y_start": 51,
      "__comment": "all other coords are based off wild card position"
    }
  },
  "status": {
    "text": {
      "x": 90,
      "y": 42,
      "short_text": false
    },
    "scrolling_text": {
      "x": 0,
      "y": 20,
      "width": 128
    }
  },
  "teams": {
    "background": {
      "away": {
        "width": 52,
        "height": 18,
        "x": 0,
        "y": 28
      },
      "home": {
        "width": 52,
        "height": 18,
        "x": 0,
        "y": 46
      }
    },
    "accent": {
      "away": {
        "width": 2,
        "height": 18,
        "x": 0,
        "y": 28
      },
      "home": {
        "width": 2,
        "height": 18,
        "x": 0,
        "y": 46
      }
    },
    "name": {
      "away": {
        "font_name": "9x18",
        "x": 4,
        "y": 42
      },
      "home": {
        "font_name": "9x18",
        "x": 4,
        "y": 60
      },
      "full": false
    },
    "record": {
      "enabled": false,
      "position": "absolute",
      "away": {
        "x": 30,
        "y": 13
      },
      "home": {
        "x": 30,
        "y": 29
      },
      "hide_record_on_high_line_score": false
    },
    "line_score": {
      "away": {
        "font_name": "9x18B",
        "x": 51,
        "y": 42
      },
      "home": {
        "font_name": "9x18B",
        "x": 51,
        "y": 60
      },
      "show_hits_and_errors": false,
      "show_abs_challenges": true,
      "compress_digits": false,
      "shorten_team_name_on_high_line_score": true,
      "spacing": 5
    },
    "abs_challenges": {
      "away": {
        "x": 53,
        "size": 2,
        "height": 8,
        "squares": [
          29,
          38
        ]
      },
      "home": {
        "x": 53,
        "size": 2,
        "height": 8,
        "squares": [
          47,
          56
        ]
      }
    }
  },
  "news": {
    "scrolling_text": {
      "x": 0,
      "y": 60,
      "width": 128
    },
    "time": {
      "x": 80,
      "y": 15
    },
    "conditions": {
      "x": 80,
      "y": 30
    },
    "temperature": {
      "x": 20,
      "y": 44
    },
    "wind_speed": {
      "x": 0,
      "y": -4
    },
    "wind_dir": {
      "x": 0,
      "y": -4
    },
    "wind": {
      "x": 80,
      "y": 44
    },
    "weather_icon": {
      "x": 6,
      "y": 2,
      "width": 30,
      "height": 30,
      "rescale_icon": 2
    }
  },
  "plugins": {},
  "network": {
    "font_name": "4x6",
    "background": {
      "width": 7,
      "height": 7,
      "x": 121,
      "y": 57
    },
    "text": {
      "x": 125,
      "y": 63
    }
  }
}
